const {Server}=require("socket.io");
const Sequelize=require('sequelize');

let io;
function createSocketServer(httpServer){
   io=new Server(httpServer,{
    cors:{
        ['http://localhost'],
        methods:['GET','POST'],
        creadentails:true,
    }
   });
   io.on('connection', (socket) => 

    socket.on('start_connection',async(info)=>{
         huiouiouioiuoioioioioiooioioioioioioiouiuiuiuiuiuiuiuiuiuiuiuiuiuiuiuiuiuiuiuiuiuiuiuioioioiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiioioioiioiiiiioioioioiooiiiiiiiuykiyufjjkjgasmndgfdnsyrfhsdngbnfbdgnbkjdfkjgkjdfbkjgkjdfgjhfgkjfdkjgkjdfkjgsdfgnkjjdfkjgdfgjdfmgkjdsfkjgmndf ghdjfghdfkjhndfkjghdnfnghdfgsgfgifdvidfvnfkjvhgfngdfgjfgdfjhgd fgkjdfbvnjfdgd gdnf gnndfjngnfdjgnfhdgbh g hdznhjgfhjbngfjnhhdfjgkjdfgbd fvfdv jb nbvxdfgdfjg fjnbvjdfg fdnjbvdf gdfjng dfgkjndfb gnfdhbnfjndnf n b vdjfbngkjdfgbdfjgkjdhfgjcvkjnbhfgnfdnsdgfdgdfgkdd,xfgjdfbkj bnbvbjhgdjfgdfbjgdfgbbfdbgfdggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggfjshgjhdfhgkjgkjhfkjdhkjfjgfjghjhfgjhfjhgjhfjhgjfhjghfghffghdhgfhjfgjhggggjhgfjghjghjghjghjghjcfhjgggghfjghjghjghjghjghjghjghjdfkjndsbghfdsgnfdhjhgsrbgtrheuithskjdgfkjsygihshjdfgkjhsuidhfgfdskngsdfhgkjdsmkvnjdhcgvfkjsfdhguhfdjhgihsdfkjnghsdfgdhjghuhsjuirdtuirueituuikjfnkjgnafghfgkjndfgnjfchvkjdkjfgnvkjxncgvbzfgkjfdghfkdszfmdfnsgmnkjbhkjudfmgbnkjdfkjghdfgajhshsjdkzkjhdfkjzhxjhfgkjdhughkjdmvnjbkjxhcvbgjdfhgnbkjvxhbjndbfkhdhfgbdfkjgbdfgnbdfgbdbnbjdxbfuhdfkjbnjdfjbdfhgdfjjkhkjhlzjghfkgldfgjgfldshdfjghkjdfvdjnvdfgsfbgnjdfbvdfhgsgkfdkjghkjdfhughaweuurituretuerhtuhreuithndsthnjgjfnjgbfgbdfkjgdfsgbkjdfbgkjvcxnbvbcgvhkbfdjkgbkjbfgbfbgvxnbcnbzvbxbvghbfdgjbdfdfbgxcvbx cbvxczbvbhkzfzlxjgkzfg.dfgldfsjkgnjdnfjgnxcnvkjxcngn kjxbkjfbgncbkjxdjbnjxcvnbxjdnbjnvcjgdfnhkdfjbgnjdfgjndfnbmjvcjkxbjkncnjxnkjcbvnknxcvkjbnkjxdnbkjndfjbnkj
    })gffdgdfhgdfhdgfhdhdfjkgdhfkjdfhgdfkjhkjdfhkjghdfkjhgkjfnv,mxc n,mbmhjznfb vmb jfjbghfkjbgm  hmzjcvb vbnxncvbmvjcb
   )  
}